### ISSUE TITLE
APIError

### ISSUE THREAD

**Issue by pruebasft** [Ponytech/appstoreconnectapi#14] opened 2020-04-22 10:32 UTC
Hi, 
I have an error when I run the script

this is my script **example.py**
```
import sys
from appstoreconnect import Api

if __name__ == "__main__":
        key_id = "XXXXXXXXXX"
        key_file = "AuthKey_XXXXXXXXXX.p8"	
        issuer_id ="XXXXXXXXXX-XXXXX-XXXXXXXXXXXXX"
        
        api = Api(key_id, key_file, issuer_id)
        apps = api.list_apps()

        print (apps)
        for app in apps:
                print(app.name)
```

The _key_file_ is in the same directory than _example.py_.
And this is the error

```
Traceback (most recent call last):
  File "C:\API_apple\example.py", line 26, in <module>
    for app in apps:
  File "C:\API_apple\appstoreconnect\api.py", line 80, in __next__
    self.fetch_page()
  File "C:\API_apple\appstoreconnect\api.py", line 97, in fetch_page
    self.payload = self.api._api_call(self.url)
  File "C:\API_apple\appstoreconnect\api.py", line 135, in _api_call
    raise APIError(payload.get('errors', [])[0].get('detail', 'Unknown error'))
appstoreconnect.api.APIError: Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
```

What is happening ?

Thanks

**Comment by ppawlak** [comment] 2020-04-22 18:29
I'm not really sure I can tell why.
In a previous version of the library we had a bug with token expiration. Which version are you using?

**Comment by pruebasft** [comment] 2020-04-23 06:47
It's this:
Version: 0.7.0

**Comment by ppawlak** [comment] 2020-04-24 08:57
> Version: 0.7.0

This should be fine with the expiration bug then.

I had just made a test. The error you have can happen if either the _key_id_  or _issuer_id_ is wrong. Can you double check them?

**Comment by ppawlak** [comment] 2020-05-20 14:12
I am closing this issue as I am not able to reproduce it.
Fell free to re-open it.

**Closed by ppawlak** 2020-05-20 14:12 UTC
